# satnogs-monitor example config

# log level 0 -> WARN, 1 -> INFO, 2 -> DEBUG, 3 -> TRACE
#log_level = 1

# If satnogs-monitor runs on the same machine as the satnogs-client, you can
# set data_path to the satnogs-client data path and get some observation data
# as it happens
#data_path = "/tmp/.satnogs/data"

#[[stations]]
# Your stations SatNOGS id
#satnogs_id = 175

# Set this to true if the monitor runs on the same machine as the SetNOGS
# ground station to get system infos (CPU temperature, Mem usage, ...).
#local = false

[ui]
# Number of orbits plotted on the map.
#ground_track_num = 3

# draw the satellite footprint on the map
#sat_footprint = true

# the spectrum_plot and waterfall widgets are only available if satnogs-monitor
# is run on the same machine as your SatNOGS station and the data_path is set to
# the satnogs-client data path
#
# enable spectrum plot
#spectrum_plot = true
#
# enable waterfall (you'll need a true color terminal)
#waterfall = true
