[package]
name = "satnogs-monitor"
version = "0.2.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
circular-queue = "0.2.2"
clap = "2.33.0"
config = "0.9.3"
directories = "2.0.2"
failure = "0.1.5"
failure_derive = "0.1.5"
gpredict = { git = "https://github.com/wose/rust-gpredict.git" }
libc = "0.2.62"
log = { version = "0.4.8", features = ["std"] }
read_color = "1.0.0"
satnogs-db-client = { path = "../satnogs-db-client" }
satnogs-network-client = { path = "../satnogs-network-client" }
serde = "1.0.101"
serde_derive = "1.0.101"
signal-hook = "0.1.10"
systemstat = { git = "https://github.com/myfreeweb/systemstat.git" }
termion = "1.5.3"
time = "0.1.42"
tui = { git = "https://github.com/wose/tui-rs.git" , features = ["termion"]}
unicode-width = "0.1.6"
