[package]
name = "satnogs-db-client"
version = "0.1.0"
authors = ["Sebastian Woetzel <wose@zuendmasse.de>"]
edition = "2018"

[dependencies]
restson = "0.5.4"
serde = "1.0.101"
serde_derive = "1.0.101"

[dev-dependencies]
mockito = "0.21.0"
